spring:
  application:
    name: Cloud-Relational-Databases-in-Action
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_rdbms
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false