spring:
  application:
    name: Cloud-Relational-Databases-in-Action

  datasource:
    url: jdbc:postgresql://localhost:12500/eca
    username: postgres
    password: psql

  data:
    rest:
      base-path: /api/v1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true