spring:
  application:
    name: Cloud-Relational-Databases-in-Action

  profiles:
    active: gcp

  data:
    rest:
      base-path: /api/v1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true